name: Deploy Support Microservice to AWS EC2

on:
  push:
    branches:
      - master
env:
  AWS_REGION: us-east-2
  EC2_INSTANCE_IP: 18.191.52.191
  EC2_USER: ec2-user
  JAR_NAME: pillihuaman-com-support-0.0.1-SNAPSHOT.jar
  APP_PORT: 8091
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Save EC2 key pair to file
        run: |
          echo "${{ secrets.EC2_KEY_PAIR_PATH }}" > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Install Java and Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk maven

      - name: Authenticate with AWS CodeArtifact and configure Maven
        run: |
          AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain pillihuamanlib \
            --domain-owner 570123367471 \
            --query authorizationToken \
            --output text)

          mkdir -p ~/.m2
          sed "s|{{AUTH_TOKEN}}|$AUTH_TOKEN|g" ci/settings-template.xml > ~/.m2/settings.xml

      - name: Build the project
        run: mvn clean install -DskipTests

      - name: Copy JAR file to EC2 instance
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no target/${{ env.JAR_NAME }} ${{ env.EC2_USER }}@${{ env.EC2_INSTANCE_IP }}:/home/${{ env.EC2_USER }}/

      - name: Restart support microservice
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_INSTANCE_IP }} << EOF
            echo "Killing previous microservice on port ${{ env.APP_PORT }}"
            PID=\$(lsof -ti tcp:${{ env.APP_PORT }}) && kill -9 \$PID || echo "No process to kill"
            echo "Starting new instance of ${{ env.JAR_NAME }}"
            nohup java -jar /home/${{ env.EC2_USER }}/${{ env.JAR_NAME }} > log_support.out 2>&1 &
          EOF
